spring:
    application:
        name: chat-app

server:
  port: 8080
  servlet:
    context-path: /chat

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081